version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: auto
    target-branch: docs
    cooldown:
      default-days: 15
    groups:
      minor-and-patch-updates:
        update-types:
          - minor
          - patch
      major-updates:
        update-types:
          - major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    cooldown:
      default-days: 15
