site_name: Theatre documentations

repo_url: https://github.com/nndda/godot-theatre/

nav:
  - "index.md"
  - "installation.md"
  - "quickstart.md"
  - "Dialogue":
    - "dialogue/writing.md"
    - "dialogue/constructing.md"
    - "dialogue/methods.md"
  - "Stage":
    - "stage/setting-up.md"

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: pink

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - content.code.copy
    - content.tooltips

markdown_extensions:
  - md_in_html
  - def_list
  - admonition
  - tables
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      # auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
