site_name: Theatre documentations

repo_url: https://github.com/nndda/Theatre
repo_name: nndda/Theatre
edit_uri: edit/docs/docs/

nav:
  - "index.md"
  - "Quick Start":
    - "installation.md"
    - "quickstart.md"
  - "Tutorials":
    - "tutorials/index.md"
    - "tutorials/minimal_setup/index.md"
    - "Basics":
      - "tutorials/basics/loading_dialogue.md"
      - "tutorials/basics/calling_dialogue_functions.md"
    - "tutorials/dialogue_ui_toggle/index.md"
    - "tutorials/dialogue_beep/index.md"
    - "tutorials/troubleshooting.md"
  - "Dialogue":
    - "class/dialogue/syntax.md"
  - "Stage":
    - "class/stage/configuration.md"

theme:
  name: material
  logo: assets/icons/Theatre-icon.png
  favicon: assets/icons/Theatre-icon.png

  palette: 
    # Palette toggle for dark mode
    # - media: "(prefers-color-scheme: dark)"
    - scheme: slate
      primary: black
      accent: blue
      # toggle:
      #   icon: material/weather-night
      #   name: Dark mode

    # # Palette toggle for light mode
    # - media: "(prefers-color-scheme: light)"
    #   scheme: light
    #   primary: black
    #   accent: pink
    #   toggle:
    #     icon: material/weather-sunny
    #     name: Light mode

  icon:
    repo: fontawesome/brands/github-alt
    edit: material/pencil
    view: material/eye
    annotation: material/arrow-right-circle

    admonition:
      note: octicons/tag-16
      info: octicons/info-16
      important: octicons/info-16
      tip: octicons/squirrel-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16

  features:
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.indexes 

    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tooltips

markdown_extensions:
  - md_in_html
  - def_list
  - admonition
  - tables
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: nndda/Theatre
      branch: docs

extra:
  social:
    - icon: simple/godotengine
      link: https://godotengine.org/asset-library/asset/2332
    - icon: simple/github
      link: https://github.com/nndda/Theatre
    - icon: simple/itchdotio
      link: https://nnda.itch.io
    - icon: simple/bluesky
      link: https://bsky.app/profile/nnda.dev
    - icon: simple/mastodon
      link: https://mastodon.art/@nnda

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/syntax.css
  - assets/stylesheets/themes.css

extra_javascript:
  - assets/scripts/heading-type.js

copyright: Copyright &copy; 2025 nnda
